# DecapCMS Configuration: Controls what you can edit in your CMS admin panel
# Access your admin panel at: yoursite.com/admin

backend:
  name: git-gateway
   repo: Ravi877/modern-blog
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "blog-posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Post", name: "featured", widget: "boolean", default: false}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "homepage"
    label: "Homepage Settings"
    files:
      - file: "site-config.json"
        label: "Site Configuration"
        name: "site_config"
        fields:
          - {label: "Site Name", name: "siteName", widget: "string"}
          - {label: "Site Description", name: "siteDescription", widget: "text"}
          - label: "Navigation Menu"
            name: "menu"
            widget: "object"
            fields:
              - {label: "Home", name: "Home", widget: "string", default: "index.html"}
              - {label: "Blog", name: "Blog", widget: "string", default: "blog.html"}
          - label: "Homepage Content"
            name: "homepage"
            widget: "object"
            fields:
              - {label: "Hero Title", name: "heroTitle", widget: "string"}
              - {label: "Hero Tagline", name: "heroTagline", widget: "text"}
              - {label: "Recent Posts Title", name: "recentPostsTitle", widget: "string", default: "Latest Posts"}
              - {label: "Number of Recent Posts", name: "recentPostsCount", widget: "number", default: 3, min: 1, max: 6}
          - label: "Footer"
            name: "footer"
            widget: "object"
            fields:
              - {label: "Footer Text", name: "text", widget: "string"}
          - label: "Blog Settings"
            name: "blog"
            widget: "object"
            fields:
              - {label: "Posts Per Page", name: "postsPerPage", widget: "number", default: 10}
              - {label: "Show Excerpts", name: "showExcerpts", widget: "boolean", default: true}
              - {label: "Excerpt Length", name: "excerptLength", widget: "number", default: 150}
