# DecapCMS settings: Defines what can be edited in the CMS.

backend:
  name: github
  repo: your-github-username/your-repo-name # <-- CHANGE THIS
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  # Collection 1: Blog Posts
  - name: "blog"
    label: "Blog"
    folder: "blog-posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename uses date and title
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featured_image", widget: "image" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

  # Collection 2: Editable Site Settings
  - name: "settings"
    label: "Site Settings"
    editor:
      preview: false
    files:
      - label: "Site Configuration"
        name: "config"
        file: "site-config.json"
        fields:
          - { label: "Site Name", name: "siteName", widget: "string" }
          - { label: "Footer Text", name: "footer", widget: "string" }
          - label: "Navigation Menu"
            name: "menu"
            widget: "object"
            fields:
              - { label: "Home", name: "Home", widget: "string", default: "index.html" }
              - { label: "Articles", name: "Articles", widget: "string", default: "blog.html" }
              - { label: "About", name: "About", widget: "string", default: "about.html" }
              - { label: "Contact", name: "Contact", widget: "string", default: "contact.html" }