# Netlify configuration for DecapCMS and site deployment
# This ensures proper routing and CMS functionality

[build]
  publish = "."
  command = "echo 'No build command needed for static site'"

# Redirect /admin to /admin/index.html for proper CMS access
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

# Enable Git Gateway for DecapCMS authentication
[build.environment]
  HUGO_VERSION = "0.54.0"
